### ISSUE TITLE
The "enchantments" and "on-use.consume" fields don't work.

### ISSUE THREAD

**Issue by luiskeniosis** [LMBishop/CommandToItem#1]
Attached is my current config file. When I get the item in game, there is no enchantment glow (tested with and without the "HIDE_ENCHANTS" item flag. When I right click the item, it disappears even though I have consume: false.
[config.zip](https://github.com/LMBishop/CommandToItem/files/3964445/config.zip)

**Comment by partydev** [comment]
Does not work for me at all either.

Edit: Was referring to the "enchantments" field. Have not used on-use.consume.

**Comment by LMBishop** [comment]
i can confirm that the "enchantments" field is not working however i cannot replicate the bug on "on-use.consume" with the given config

can you confirm you're using the latest version, 2.3?

**Comment by Marotheit** [comment]
I am also having an issue with `on-use.consume`.

I am running Paper #31 for 1.15.1, CommandToItem v2.3.

I even tried running the default infinite-cookie example, and it too disappears.

[config.zip](https://github.com/LMBishop/CommandToItem/files/4006195/config.zip)
