### ISSUE TITLE
Allow no command

### ISSUE THREAD

**Issue by alpoi-old** [LMBishop/CommandToItem#13]
Potentially odd suggestion given the name and function of the plugin:
Would it be possible to make `on-use.commands` optional? I like to use your plugin to save specific items to give in crates (your layout is by far the best for name/lore/enchants/attributes etc). It would be nice if the item didn't require command functionality!

**Comment by LMBishop** [comment]
You could try setting it to an empty array:
```
...:
  on-use:
    commands: []
```

That should, in theory, make the plugin process no commands

**Comment by alpoi-old** [comment]
Worked perfectly, you're amazing thanks!
