### ISSUE TITLE
An error message when using plugin with Betterrtp

### ISSUE THREAD

**Issue by MusicTW** [LMBishop/CommandToItem#7]
rtp:
    name: "&f隨機&5傳送&f卷軸"
    lore:
      - "&c一次性產品&f，使用時將會被隨機&c傳送至千里之外"
      - "&4備註：只能在主世界使用"
      - "&f 右鍵 | 使用卷軸"
    item: PAPER
    on-use:
      commands:
        - "rtp player %player% world"
        
        error message when I was using it
        https://paste.in/nIkp35

**Comment by LMBishop** [comment]
This does not appear to be an issue with CommandToItem, but your random TP plugin instead. Although from the error it appears as if the plugin is expecting the console to execute that command, so try prepending "executeas:console" to the start of the command.
